In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import *
from tensorflow.keras.model import Sequential
from tensorflow.keras.layers import Dense

ModuleNotFoundError: No module named 'tensorflow.keras.model'

Prepare data for trainning

In [8]:
X = np.zeros((1000,3))
Y = np.zeros((1000,3))

In [18]:
X,Y

(array([[[   2.],
         [   3.],
         [   4.]],
 
        [[   3.],
         [   4.],
         [   5.]],
 
        [[   4.],
         [   5.],
         [   6.]],
 
        ...,
 
        [[ 999.],
         [1000.],
         [1001.]],
 
        [[1000.],
         [1001.],
         [1002.]],
 
        [[1001.],
         [1002.],
         [1003.]]]),
 array([[[   5.],
         [   6.],
         [   7.]],
 
        [[   6.],
         [   7.],
         [   8.]],
 
        [[   7.],
         [   8.],
         [   9.]],
 
        ...,
 
        [[1002.],
         [1003.],
         [1004.]],
 
        [[1003.],
         [1004.],
         [1005.]],
 
        [[1004.],
         [1005.],
         [1006.]]]))

In [10]:
for i in range (1,1001):
    X[i-1] = [i+1,i+2,i+3]
    Y[i-1] = [i+4,i+5,i+6]

In [11]:
X = X.reshape((1000,3,1))
Y = Y.reshape((1000,3,1))

(array([[   2.,    3.,    4.],
        [   3.,    4.,    5.],
        [   4.,    5.,    6.],
        ...,
        [ 999., 1000., 1001.],
        [1000., 1001., 1002.],
        [1001., 1002., 1003.]]),
 array([[   5.,    6.,    7.],
        [   6.,    7.,    8.],
        [   7.,    8.,    9.],
        ...,
        [1002., 1003., 1004.],
        [1003., 1004., 1005.],
        [1004., 1005., 1006.]]))

Build model

In [ ]:
model = Sequential()

model.add(LSTM(22, input_shape=(1000, 3,1)))
model.add(Dense(22, activation='relu'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(train_input, train_output, epochs=20, batch_size=100)