In [20]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import *
from tensorflow.keras.layers import Dense,LSTM,TimeDistributed

Prepare data for trainning

In [51]:
X = np.zeros((1000,3))
Y = np.zeros((1000,3))

In [52]:
X,Y

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [53]:
for i in range (1,1001):
    X[i-1] = [i+1,i+2,i+3]
    Y[i-1] = [i+4,i+5,i+6]

In [54]:
X = X.reshape((1000,3,1))/1000
Y = Y.reshape((1000,3,1))/1000
X,Y

(array([[[0.002],
         [0.003],
         [0.004]],
 
        [[0.003],
         [0.004],
         [0.005]],
 
        [[0.004],
         [0.005],
         [0.006]],
 
        ...,
 
        [[0.999],
         [1.   ],
         [1.001]],
 
        [[1.   ],
         [1.001],
         [1.002]],
 
        [[1.001],
         [1.002],
         [1.003]]]),
 array([[[0.005],
         [0.006],
         [0.007]],
 
        [[0.006],
         [0.007],
         [0.008]],
 
        [[0.007],
         [0.008],
         [0.009]],
 
        ...,
 
        [[1.002],
         [1.003],
         [1.004]],
 
        [[1.003],
         [1.004],
         [1.005]],
 
        [[1.004],
         [1.005],
         [1.006]]]))

Build model

In [89]:
model = Sequential()

model.add(LSTM(20,return_sequences=True, input_shape=(3,1))) #return_sequences=False
#model.add(LSTM(3, activation='relu'))
#model.add(TimeDistributed(Dense(100, activation='relu')))
model.add(TimeDistributed(Dense(1, activation='relu')))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
print(model.summary())


Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_27 (LSTM)               (None, 3, 20)             1760      
_________________________________________________________________
time_distributed_20 (TimeDis (None, 3, 1)              21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________
None


In [94]:
model.fit(X, Y, epochs=1000, validation_split=0.3, shuffle=True,batch_size=500)

Train on 700 samples, validate on 300 samples
Epoch 1/1000
700/700 [==============================] - 0s 127us/sample - loss: 7.0594e-07 - accuracy: 0.0000e+00 - val_loss: 1.1597e-05 - val_accuracy: 0.0033
Epoch 2/1000
700/700 [==============================] - 0s 129us/sample - loss: 7.0357e-07 - accuracy: 0.0000e+00 - val_loss: 1.1643e-05 - val_accuracy: 0.0033
Epoch 3/1000
700/700 [==============================] - 0s 137us/sample - loss: 7.0053e-07 - accuracy: 0.0000e+00 - val_loss: 1.1540e-05 - val_accuracy: 0.0033
Epoch 4/1000
700/700 [==============================] - 0s 124us/sample - loss: 6.9777e-07 - accuracy: 0.0000e+00 - val_loss: 1.1486e-05 - val_accuracy: 0.0033
Epoch 5/1000
700/700 [==============================] - 0s 127us/sample - loss: 6.9536e-07 - accuracy: 0.0000e+00 - val_loss: 1.1542e-05 - val_accuracy: 0.0033
Epoch 6/1000
700/700 [==============================] - 0s 100us/sample - loss: 6.9288e-07 - accuracy: 0.0000e+00 - val_loss: 1.1747e-05 - val_accuracy: 0

700/700 [==============================] - 0s 69us/sample - loss: 5.8134e-07 - accuracy: 0.0000e+00 - val_loss: 1.3072e-05 - val_accuracy: 0.0033
Epoch 52/1000
700/700 [==============================] - 0s 69us/sample - loss: 5.7899e-07 - accuracy: 0.0000e+00 - val_loss: 1.2978e-05 - val_accuracy: 0.0033
Epoch 53/1000
700/700 [==============================] - 0s 64us/sample - loss: 5.7674e-07 - accuracy: 0.0000e+00 - val_loss: 1.3068e-05 - val_accuracy: 0.0033
Epoch 54/1000
700/700 [==============================] - 0s 63us/sample - loss: 5.7442e-07 - accuracy: 0.0000e+00 - val_loss: 1.3242e-05 - val_accuracy: 0.0033
Epoch 55/1000
700/700 [==============================] - 0s 60us/sample - loss: 5.7207e-07 - accuracy: 0.0000e+00 - val_loss: 1.3372e-05 - val_accuracy: 0.0033
Epoch 56/1000
700/700 [==============================] - 0s 54us/sample - loss: 5.7019e-07 - accuracy: 0.0000e+00 - val_loss: 1.3410e-05 - val_accuracy: 0.0033
Epoch 57/1000
700/700 [==============================]

700/700 [==============================] - 0s 70us/sample - loss: 4.7776e-07 - accuracy: 0.0000e+00 - val_loss: 1.5206e-05 - val_accuracy: 0.0033
Epoch 103/1000
700/700 [==============================] - 0s 71us/sample - loss: 4.7598e-07 - accuracy: 0.0000e+00 - val_loss: 1.5214e-05 - val_accuracy: 0.0033
Epoch 104/1000
700/700 [==============================] - 0s 63us/sample - loss: 4.7408e-07 - accuracy: 0.0000e+00 - val_loss: 1.5407e-05 - val_accuracy: 0.0033
Epoch 105/1000
700/700 [==============================] - 0s 66us/sample - loss: 4.7218e-07 - accuracy: 0.0000e+00 - val_loss: 1.5517e-05 - val_accuracy: 0.0033
Epoch 106/1000
700/700 [==============================] - 0s 61us/sample - loss: 4.7051e-07 - accuracy: 0.0000e+00 - val_loss: 1.5497e-05 - val_accuracy: 0.0033
Epoch 107/1000
700/700 [==============================] - 0s 64us/sample - loss: 4.6863e-07 - accuracy: 0.0000e+00 - val_loss: 1.5449e-05 - val_accuracy: 0.0033
Epoch 108/1000
700/700 [=========================

Epoch 153/1000
700/700 [==============================] - 0s 51us/sample - loss: 3.9493e-07 - accuracy: 0.0000e+00 - val_loss: 1.7549e-05 - val_accuracy: 0.0033
Epoch 154/1000
700/700 [==============================] - 0s 44us/sample - loss: 3.9350e-07 - accuracy: 0.0000e+00 - val_loss: 1.7641e-05 - val_accuracy: 0.0033
Epoch 155/1000
700/700 [==============================] - 0s 44us/sample - loss: 3.9210e-07 - accuracy: 0.0000e+00 - val_loss: 1.7768e-05 - val_accuracy: 0.0033
Epoch 156/1000
700/700 [==============================] - 0s 49us/sample - loss: 3.9083e-07 - accuracy: 0.0000e+00 - val_loss: 1.7778e-05 - val_accuracy: 0.0033
Epoch 157/1000
700/700 [==============================] - 0s 46us/sample - loss: 3.8940e-07 - accuracy: 0.0000e+00 - val_loss: 1.7698e-05 - val_accuracy: 0.0033
Epoch 158/1000
700/700 [==============================] - 0s 43us/sample - loss: 3.8796e-07 - accuracy: 0.0000e+00 - val_loss: 1.7753e-05 - val_accuracy: 0.0033
Epoch 159/1000
700/700 [==========

Epoch 204/1000
700/700 [==============================] - 0s 47us/sample - loss: 3.3020e-07 - accuracy: 0.0000e+00 - val_loss: 2.0246e-05 - val_accuracy: 0.0033
Epoch 205/1000
700/700 [==============================] - 0s 43us/sample - loss: 3.2947e-07 - accuracy: 0.0000e+00 - val_loss: 2.0286e-05 - val_accuracy: 0.0033
Epoch 206/1000
700/700 [==============================] - 0s 39us/sample - loss: 3.2795e-07 - accuracy: 0.0000e+00 - val_loss: 2.0070e-05 - val_accuracy: 0.0033
Epoch 207/1000
700/700 [==============================] - 0s 41us/sample - loss: 3.2718e-07 - accuracy: 0.0000e+00 - val_loss: 2.0104e-05 - val_accuracy: 0.0033
Epoch 208/1000
700/700 [==============================] - 0s 41us/sample - loss: 3.2610e-07 - accuracy: 0.0000e+00 - val_loss: 2.0367e-05 - val_accuracy: 0.0033
Epoch 209/1000
700/700 [==============================] - 0s 39us/sample - loss: 3.2476e-07 - accuracy: 0.0000e+00 - val_loss: 2.0608e-05 - val_accuracy: 0.0033
Epoch 210/1000
700/700 [==========

Epoch 255/1000
700/700 [==============================] - 0s 47us/sample - loss: 2.8063e-07 - accuracy: 0.0000e+00 - val_loss: 2.2861e-05 - val_accuracy: 0.0033
Epoch 256/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.7985e-07 - accuracy: 0.0000e+00 - val_loss: 2.2809e-05 - val_accuracy: 0.0033
Epoch 257/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.7897e-07 - accuracy: 0.0000e+00 - val_loss: 2.2718e-05 - val_accuracy: 0.0033
Epoch 258/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.7825e-07 - accuracy: 0.0000e+00 - val_loss: 2.2684e-05 - val_accuracy: 0.0033
Epoch 259/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.7754e-07 - accuracy: 0.0000e+00 - val_loss: 2.2884e-05 - val_accuracy: 0.0033
Epoch 260/1000
700/700 [==============================] - 0s 43us/sample - loss: 2.7649e-07 - accuracy: 0.0000e+00 - val_loss: 2.3126e-05 - val_accuracy: 0.0033
Epoch 261/1000
700/700 [==========

Epoch 306/1000
700/700 [==============================] - 0s 47us/sample - loss: 2.4397e-07 - accuracy: 0.0000e+00 - val_loss: 2.5405e-05 - val_accuracy: 0.0033
Epoch 307/1000
700/700 [==============================] - 0s 39us/sample - loss: 2.4348e-07 - accuracy: 0.0000e+00 - val_loss: 2.5360e-05 - val_accuracy: 0.0033
Epoch 308/1000
700/700 [==============================] - 0s 39us/sample - loss: 2.4266e-07 - accuracy: 0.0000e+00 - val_loss: 2.5281e-05 - val_accuracy: 0.0033
Epoch 309/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.4223e-07 - accuracy: 0.0000e+00 - val_loss: 2.5388e-05 - val_accuracy: 0.0033
Epoch 310/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.4143e-07 - accuracy: 0.0000e+00 - val_loss: 2.5607e-05 - val_accuracy: 0.0033
Epoch 311/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.4099e-07 - accuracy: 0.0000e+00 - val_loss: 2.5581e-05 - val_accuracy: 0.0033
Epoch 312/1000
700/700 [==========

Epoch 357/1000
700/700 [==============================] - 0s 43us/sample - loss: 2.1759e-07 - accuracy: 0.0000e+00 - val_loss: 2.7345e-05 - val_accuracy: 0.0033
Epoch 358/1000
700/700 [==============================] - 0s 40us/sample - loss: 2.1710e-07 - accuracy: 0.0000e+00 - val_loss: 2.7719e-05 - val_accuracy: 0.0033
Epoch 359/1000
700/700 [==============================] - 0s 37us/sample - loss: 2.1645e-07 - accuracy: 0.0000e+00 - val_loss: 2.7948e-05 - val_accuracy: 0.0033
Epoch 360/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.1636e-07 - accuracy: 0.0000e+00 - val_loss: 2.7809e-05 - val_accuracy: 0.0033
Epoch 361/1000
700/700 [==============================] - 0s 41us/sample - loss: 2.1564e-07 - accuracy: 0.0000e+00 - val_loss: 2.7671e-05 - val_accuracy: 0.0033
Epoch 362/1000
700/700 [==============================] - 0s 40us/sample - loss: 2.1525e-07 - accuracy: 0.0000e+00 - val_loss: 2.7800e-05 - val_accuracy: 0.0033
Epoch 363/1000
700/700 [==========

Epoch 408/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.9864e-07 - accuracy: 0.0000e+00 - val_loss: 2.9581e-05 - val_accuracy: 0.0033
Epoch 409/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.9769e-07 - accuracy: 0.0000e+00 - val_loss: 2.9973e-05 - val_accuracy: 0.0033
Epoch 410/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.9781e-07 - accuracy: 0.0000e+00 - val_loss: 3.0065e-05 - val_accuracy: 0.0033
Epoch 411/1000
700/700 [==============================] - 0s 39us/sample - loss: 1.9749e-07 - accuracy: 0.0000e+00 - val_loss: 2.9818e-05 - val_accuracy: 0.0033
Epoch 412/1000
700/700 [==============================] - 0s 39us/sample - loss: 1.9701e-07 - accuracy: 0.0000e+00 - val_loss: 2.9782e-05 - val_accuracy: 0.0033
Epoch 413/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.9676e-07 - accuracy: 0.0000e+00 - val_loss: 2.9980e-05 - val_accuracy: 0.0033
Epoch 414/1000
700/700 [==========

Epoch 459/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.8477e-07 - accuracy: 0.0000e+00 - val_loss: 3.1637e-05 - val_accuracy: 0.0033
Epoch 460/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.8445e-07 - accuracy: 0.0000e+00 - val_loss: 3.1483e-05 - val_accuracy: 0.0033
Epoch 461/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.8444e-07 - accuracy: 0.0000e+00 - val_loss: 3.1612e-05 - val_accuracy: 0.0033
Epoch 462/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.8395e-07 - accuracy: 0.0000e+00 - val_loss: 3.1719e-05 - val_accuracy: 0.0033
Epoch 463/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.8383e-07 - accuracy: 0.0000e+00 - val_loss: 3.1758e-05 - val_accuracy: 0.0033
Epoch 464/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.8371e-07 - accuracy: 0.0000e+00 - val_loss: 3.1662e-05 - val_accuracy: 0.0033
Epoch 465/1000
700/700 [==========

Epoch 510/1000
700/700 [==============================] - 0s 49us/sample - loss: 1.7563e-07 - accuracy: 0.0000e+00 - val_loss: 3.3223e-05 - val_accuracy: 0.0033
Epoch 511/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.7541e-07 - accuracy: 0.0000e+00 - val_loss: 3.3522e-05 - val_accuracy: 0.0033
Epoch 512/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.7537e-07 - accuracy: 0.0000e+00 - val_loss: 3.3422e-05 - val_accuracy: 0.0033
Epoch 513/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.7488e-07 - accuracy: 0.0000e+00 - val_loss: 3.3084e-05 - val_accuracy: 0.0033
Epoch 514/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.7527e-07 - accuracy: 0.0000e+00 - val_loss: 3.3097e-05 - val_accuracy: 0.0033
Epoch 515/1000
700/700 [==============================] - 0s 46us/sample - loss: 1.7487e-07 - accuracy: 0.0000e+00 - val_loss: 3.3378e-05 - val_accuracy: 0.0033
Epoch 516/1000
700/700 [==========

Epoch 561/1000
700/700 [==============================] - 0s 47us/sample - loss: 1.6905e-07 - accuracy: 0.0000e+00 - val_loss: 3.4552e-05 - val_accuracy: 0.0033
Epoch 562/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.6910e-07 - accuracy: 0.0000e+00 - val_loss: 3.4650e-05 - val_accuracy: 0.0033
Epoch 563/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.6879e-07 - accuracy: 0.0000e+00 - val_loss: 3.4919e-05 - val_accuracy: 0.0033
Epoch 564/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.6921e-07 - accuracy: 0.0000e+00 - val_loss: 3.4827e-05 - val_accuracy: 0.0033
Epoch 565/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.6866e-07 - accuracy: 0.0000e+00 - val_loss: 3.4524e-05 - val_accuracy: 0.0033
Epoch 566/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.6907e-07 - accuracy: 0.0000e+00 - val_loss: 3.4711e-05 - val_accuracy: 0.0033
Epoch 567/1000
700/700 [==========

Epoch 612/1000
700/700 [==============================] - 0s 47us/sample - loss: 1.6526e-07 - accuracy: 0.0000e+00 - val_loss: 3.5367e-05 - val_accuracy: 0.0033
Epoch 613/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.6534e-07 - accuracy: 0.0000e+00 - val_loss: 3.5571e-05 - val_accuracy: 0.0033
Epoch 614/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.6501e-07 - accuracy: 0.0000e+00 - val_loss: 3.5679e-05 - val_accuracy: 0.0033
Epoch 615/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.6482e-07 - accuracy: 0.0000e+00 - val_loss: 3.5567e-05 - val_accuracy: 0.0033
Epoch 616/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.6468e-07 - accuracy: 0.0000e+00 - val_loss: 3.5485e-05 - val_accuracy: 0.0033
Epoch 617/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.6497e-07 - accuracy: 0.0000e+00 - val_loss: 3.5736e-05 - val_accuracy: 0.0033
Epoch 618/1000
700/700 [==========

Epoch 663/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.6246e-07 - accuracy: 0.0000e+00 - val_loss: 3.6728e-05 - val_accuracy: 0.0033
Epoch 664/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.6202e-07 - accuracy: 0.0000e+00 - val_loss: 3.6412e-05 - val_accuracy: 0.0033
Epoch 665/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.6278e-07 - accuracy: 0.0000e+00 - val_loss: 3.6726e-05 - val_accuracy: 0.0033
Epoch 666/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.6236e-07 - accuracy: 0.0000e+00 - val_loss: 3.7028e-05 - val_accuracy: 0.0033
Epoch 667/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.6265e-07 - accuracy: 0.0000e+00 - val_loss: 3.6688e-05 - val_accuracy: 0.0033
Epoch 668/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.6188e-07 - accuracy: 0.0000e+00 - val_loss: 3.6668e-05 - val_accuracy: 0.0033
Epoch 669/1000
700/700 [==========

Epoch 714/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.6054e-07 - accuracy: 0.0000e+00 - val_loss: 3.7079e-05 - val_accuracy: 0.0033
Epoch 715/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.6032e-07 - accuracy: 0.0000e+00 - val_loss: 3.7229e-05 - val_accuracy: 0.0033
Epoch 716/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5996e-07 - accuracy: 0.0000e+00 - val_loss: 3.7683e-05 - val_accuracy: 0.0033
Epoch 717/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.6107e-07 - accuracy: 0.0000e+00 - val_loss: 3.7620e-05 - val_accuracy: 0.0033
Epoch 718/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.6051e-07 - accuracy: 0.0000e+00 - val_loss: 3.7027e-05 - val_accuracy: 0.0033
Epoch 719/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.6116e-07 - accuracy: 0.0000e+00 - val_loss: 3.7218e-05 - val_accuracy: 0.0033
Epoch 720/1000
700/700 [==========

Epoch 765/1000
700/700 [==============================] - 0s 47us/sample - loss: 1.5887e-07 - accuracy: 0.0000e+00 - val_loss: 3.7806e-05 - val_accuracy: 0.0033
Epoch 766/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5878e-07 - accuracy: 0.0000e+00 - val_loss: 3.7743e-05 - val_accuracy: 0.0033
Epoch 767/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.5898e-07 - accuracy: 0.0000e+00 - val_loss: 3.8034e-05 - val_accuracy: 0.0033
Epoch 768/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.5862e-07 - accuracy: 0.0000e+00 - val_loss: 3.7987e-05 - val_accuracy: 0.0033
Epoch 769/1000
700/700 [==============================] - 0s 46us/sample - loss: 1.5851e-07 - accuracy: 0.0000e+00 - val_loss: 3.7970e-05 - val_accuracy: 0.0033
Epoch 770/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5864e-07 - accuracy: 0.0000e+00 - val_loss: 3.7926e-05 - val_accuracy: 0.0033
Epoch 771/1000
700/700 [==========

Epoch 816/1000
700/700 [==============================] - 0s 46us/sample - loss: 1.5750e-07 - accuracy: 0.0000e+00 - val_loss: 3.8419e-05 - val_accuracy: 0.0033
Epoch 817/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5784e-07 - accuracy: 0.0000e+00 - val_loss: 3.8290e-05 - val_accuracy: 0.0033
Epoch 818/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5773e-07 - accuracy: 0.0000e+00 - val_loss: 3.8045e-05 - val_accuracy: 0.0033
Epoch 819/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5800e-07 - accuracy: 0.0000e+00 - val_loss: 3.8422e-05 - val_accuracy: 0.0033
Epoch 820/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5774e-07 - accuracy: 0.0000e+00 - val_loss: 3.8636e-05 - val_accuracy: 0.0033
Epoch 821/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5806e-07 - accuracy: 0.0000e+00 - val_loss: 3.8187e-05 - val_accuracy: 0.0033
Epoch 822/1000
700/700 [==========

Epoch 867/1000
700/700 [==============================] - 0s 49us/sample - loss: 1.5706e-07 - accuracy: 0.0000e+00 - val_loss: 3.8518e-05 - val_accuracy: 0.0033
Epoch 868/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5668e-07 - accuracy: 0.0000e+00 - val_loss: 3.8352e-05 - val_accuracy: 0.0033
Epoch 869/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5699e-07 - accuracy: 0.0000e+00 - val_loss: 3.8383e-05 - val_accuracy: 0.0033
Epoch 870/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.5670e-07 - accuracy: 0.0000e+00 - val_loss: 3.8540e-05 - val_accuracy: 0.0033
Epoch 871/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5678e-07 - accuracy: 0.0000e+00 - val_loss: 3.8560e-05 - val_accuracy: 0.0033
Epoch 872/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.5680e-07 - accuracy: 0.0000e+00 - val_loss: 3.8320e-05 - val_accuracy: 0.0033
Epoch 873/1000
700/700 [==========

Epoch 918/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5584e-07 - accuracy: 0.0000e+00 - val_loss: 3.8383e-05 - val_accuracy: 0.0033
Epoch 919/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5656e-07 - accuracy: 0.0000e+00 - val_loss: 3.8762e-05 - val_accuracy: 0.0033
Epoch 920/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5617e-07 - accuracy: 0.0000e+00 - val_loss: 3.9023e-05 - val_accuracy: 0.0033
Epoch 921/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5659e-07 - accuracy: 0.0000e+00 - val_loss: 3.8553e-05 - val_accuracy: 0.0033
Epoch 922/1000
700/700 [==============================] - 0s 40us/sample - loss: 1.5649e-07 - accuracy: 0.0000e+00 - val_loss: 3.8543e-05 - val_accuracy: 0.0033
Epoch 923/1000
700/700 [==============================] - 0s 43us/sample - loss: 1.5585e-07 - accuracy: 0.0000e+00 - val_loss: 3.9171e-05 - val_accuracy: 0.0033
Epoch 924/1000
700/700 [==========

Epoch 969/1000
700/700 [==============================] - 0s 46us/sample - loss: 1.5520e-07 - accuracy: 0.0000e+00 - val_loss: 3.8554e-05 - val_accuracy: 0.0033
Epoch 970/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5512e-07 - accuracy: 0.0000e+00 - val_loss: 3.8412e-05 - val_accuracy: 0.0033
Epoch 971/1000
700/700 [==============================] - 0s 44us/sample - loss: 1.5534e-07 - accuracy: 0.0000e+00 - val_loss: 3.8683e-05 - val_accuracy: 0.0033
Epoch 972/1000
700/700 [==============================] - 0s 46us/sample - loss: 1.5520e-07 - accuracy: 0.0000e+00 - val_loss: 3.8826e-05 - val_accuracy: 0.0033
Epoch 973/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5540e-07 - accuracy: 0.0000e+00 - val_loss: 3.8398e-05 - val_accuracy: 0.0033
Epoch 974/1000
700/700 [==============================] - 0s 41us/sample - loss: 1.5586e-07 - accuracy: 0.0000e+00 - val_loss: 3.8473e-05 - val_accuracy: 0.0033
Epoch 975/1000
700/700 [==========

In [95]:
model.predict([[[0.001],[0.002],[0.003]]])*1000

array([[[5.7784953],
        [5.6550055],
        [6.2746105]]], dtype=float32)