In [50]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import *
from tensorflow.keras.layers import Dense,LSTM,TimeDistributed

Prepare data for trainning

In [51]:
X = np.zeros((1000,3))
Y = np.zeros((1000,3))
for i in range (1,1001):
    X[i-1] = [i+1,i+2,i+3]
    Y[i-1] = [i+4,i+5,i+6]

X = X.reshape((1000,3,1))/1000
Y = Y.reshape((1000,3,1))/1000
X,Y  

(array([[[0.002],
         [0.003],
         [0.004]],
 
        [[0.003],
         [0.004],
         [0.005]],
 
        [[0.004],
         [0.005],
         [0.006]],
 
        ...,
 
        [[0.999],
         [1.   ],
         [1.001]],
 
        [[1.   ],
         [1.001],
         [1.002]],
 
        [[1.001],
         [1.002],
         [1.003]]]),
 array([[[0.005],
         [0.006],
         [0.007]],
 
        [[0.006],
         [0.007],
         [0.008]],
 
        [[0.007],
         [0.008],
         [0.009]],
 
        ...,
 
        [[1.002],
         [1.003],
         [1.004]],
 
        [[1.003],
         [1.004],
         [1.005]],
 
        [[1.004],
         [1.005],
         [1.006]]]))

Build model

In [79]:
model = Sequential()

model.add(LSTM(32, input_shape=(3,1))) #return_sequences=False
#model.add(LSTM(3, return_sequences=True, activation='relu'))
#model.add(TimeDistributed(Dense(1, activation='relu')))
model.add(Dense(3, activation='relu'))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
print(model.summary())


Model: "sequential_29"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_34 (LSTM)               (None, 32)                4352      
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 99        
Total params: 4,451
Trainable params: 4,451
Non-trainable params: 0
_________________________________________________________________
None


In [80]:
model.fit(X, Y, epochs=1000, validation_split=0.3, shuffle=True) #,batch_size=500

Epoch 1/1000


ValueError: in user code:

    c:\program files\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    c:\program files\python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:543 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    c:\program files\python38\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:411 update_state
        metric_obj.update_state(y_t, y_p)
    c:\program files\python38\lib\site-packages\tensorflow\python\keras\utils\metrics_utils.py:90 decorated
        update_op = update_state_fn(*args, **kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\keras\metrics.py:603 update_state
        matches = self._fn(y_true, y_pred, **self._fn_kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\keras\metrics.py:3244 sparse_categorical_accuracy
        y_true = array_ops.squeeze(y_true, [-1])
    c:\program files\python38\lib\site-packages\tensorflow\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\util\deprecation.py:507 new_func
        return func(*args, **kwargs)
    c:\program files\python38\lib\site-packages\tensorflow\python\ops\array_ops.py:4145 squeeze
        return gen_array_ops.squeeze(input, axis, name)
    c:\program files\python38\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:9874 squeeze
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    c:\program files\python38\lib\site-packages\tensorflow\python\framework\op_def_library.py:742 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    c:\program files\python38\lib\site-packages\tensorflow\python\framework\func_graph.py:593 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    c:\program files\python38\lib\site-packages\tensorflow\python\framework\ops.py:3319 _create_op_internal
        ret = Operation(
    c:\program files\python38\lib\site-packages\tensorflow\python\framework\ops.py:1816 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    c:\program files\python38\lib\site-packages\tensorflow\python\framework\ops.py:1657 _create_c_op
        raise ValueError(str(e))

    ValueError: Can not squeeze dim[1], expected a dimension of 1, got 3 for '{{node Squeeze}} = Squeeze[T=DT_FLOAT, squeeze_dims=[-1]](remove_squeezable_dimensions/Squeeze)' with input shapes: [?,3].


In [78]:
model.predict([[[0.001],[0.002],[0.003]]])*1000

array([[5.4228363]], dtype=float32)